###
PUT http://ec2-3-89-206-171.compute-1.amazonaws.com/alumnos/1 HTTP/1.1
Content-Type: application/json

{
  "promedio": 56.0
}

###
GET http://ec2-3-89-206-171.compute-1.amazonaws.com/alumnos HTTP/1.1
Content-Type: application/json

###
POST http://ec2-3-89-206-171.compute-1.amazonaws.com/profesores HTTP/1.1
Content-Type: application/json

{
  "id": 1,
  "nombres": "Ana",
  "apellidos": "Lopez",
  "numeroEmpleado": "654321",
  "horasClase": 20
}

###
DELETE http://ec2-3-89-206-171.compute-1.amazonaws.com/profesores/1 HTTP/1.1
Content-Type: application/json

###
PUT http://ec2-3-89-206-171.compute-1.amazonaws.com/profesores/1 HTTP/1.1
Content-Type: application/json

{
  "horasClase": 25
}

###
POST http://ec2-3-89-206-171.compute-1.amazonaws.com/alumnos HTTP/1.1
Content-Type: application/json

{
  "nombres": "Carlos",
  "apellidos": "Lopez",
  "matricula": "A345678",
  "promedio": 88.0,
  "password": "pass789"
}

###
GET http://ec2-3-89-206-171.compute-1.amazonaws.com/alumnos HTTP/1.1
Content-Type: application/json

###
POST http://ec2-3-89-206-171.compute-1.amazonaws.com/alumnos HTTP/1.1
Content-Type: application/json

{
  "nombres": "Maria",
  "apellidos": "Garcia",
  "matricula": "A555666",
  "promedio": 95.0,
  "password": "test123"
}

###
POST http://ec2-3-89-206-171.compute-1.amazonaws.com/alumnos/1/email HTTP/1.1
Content-Type: application/json


###
POST http://ec2-3-89-206-171.compute-1.amazonaws.com/alumnos HTTP/1.1
Content-Type: application/json

{
  "nombres": "Test",
  "apellidos": "DynamoDB",
  "matricula": "A111111",
  "promedio": 90.0,
  "password": "test123"
}

###
POST http://ec2-3-89-206-171.compute-1.amazonaws.com/alumnos/1/session/login HTTP/1.1
Content-Type: application/json

{
  "password": "pass789"
}