###
# Créer un alumno dans RDS MySQL
POST http://127.0.0.1:5000/alumnos HTTP/1.1
Content-Type: application/json

{
  "nombres": "Pedro",
  "apellidos": "Martinez",
  "matricula": "A999888",
  "promedio": 91.5,
  "password": "testpass"
}

###
# Récupérer tous les alumnos
GET http://127.0.0.1:5000/alumnos HTTP/1.1
Content-Type: application/json

###

GET http://127.0.0.1:5000/alumnos/3 HTTP/1.1
Content-Type: application/json

###
# Test 1 : Créer un alumno avec password
POST http://127.0.0.1:5000/alumnos HTTP/1.1
Content-Type: application/json

{
  "nombres": "Juan",
  "apellidos": "Perez",
  "matricula": "A123456",
  "promedio": 85.5,
  "password": "secret123"
}

###
# Test 2 : Récupérer l'alumno (doit inclure password et fotoPerfilUrl)
GET http://127.0.0.1:5000/alumnos/3 HTTP/1.1
Content-Type: application/json

###
# Test 3 : Upload d'une photo de profil
# ⚠️ Ce test ne peut PAS être fait avec .rest (multipart/form-data)
# Utiliser Postman ou curl (voir ci-dessous)

###
DELETE http://127.0.0.1:5000/alumnos/2 HTTP/1.1
Content-Type: application/json

###
PUT http://ec2-98-86-226-154.compute-1.amazonaws.com/alumnos/1 HTTP/1.1
Content-Type: application/json

{
  "promedio": 56.0
}

###
GET http://ec2-13-217-97-65.compute-1.amazonaws.com/alumnos HTTP/1.1
Content-Type: application/json

###
POST http://ec2-13-217-97-65.compute-1.amazonaws.com/profesores HTTP/1.1
Content-Type: application/json

{
  "id": 1,
  "nombres": "Ana",
  "apellidos": "Lopez",
  "numeroEmpleado": "654321",
  "horasClase": 20
}

###
DELETE http://ec2-98-86-226-154.compute-1.amazonaws.com/profesores/1 HTTP/1.1
Content-Type: application/json

###
PUT http://ec2-98-86-226-154.compute-1.amazonaws.com/profesores/1 HTTP/1.1
Content-Type: application/json

{
  "horasClase": 25
}

###
# Test sur EC2 (RDS)
POST http://ec2-3-90-151-247.compute-1.amazonaws.com/alumnos HTTP/1.1
Content-Type: application/json

{
  "nombres": "Carlos",
  "apellidos": "Lopez",
  "matricula": "A345678",
  "promedio": 88.0,
  "password": "pass789"
}

###
GET http://ec2-3-90-151-247.compute-1.amazonaws.com/alumnos HTTP/1.1
Content-Type: application/json

###
# Créer un alumno test
POST http://127.0.0.1:5000/alumnos HTTP/1.1
Content-Type: application/json

{
  "nombres": "Maria",
  "apellidos": "Garcia",
  "matricula": "A555666",
  "promedio": 95.0,
  "password": "test123"
}

###
# Envoyer une notification pour l'alumno créé
# Remplacer {id} par l'ID retourné ci-dessus
POST http://127.0.0.1:5000/alumnos/1/email HTTP/1.1
Content-Type: application/json